version: "3"

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    env_file: ./.env

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./gateway:/go/src/app
    tty: true
    stdin_open: true
    ports:
      - 2000:2000
    depends_on:
      - staff_api
      - federation
    env_file: ./.env

  federation:
    build:
      context: ./federation
      dockerfile: Dockerfile
    volumes:
      - ./federation:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - staff_api:staff_api
      - user_api:user_api
      - inquiry_api:inquiry_api
    depends_on:
      - staff_api
      - user_api
      - inquiry_api
    env_file: ./.env
    command: npm run dev

  staff_api:
    build:
      context: ./staff_api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./staff_api:/go/src/app
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
      - 50051:50051
    depends_on:
      - db
    env_file: ./.env

  staff_db_gui:
    image: sosedoff/pgweb
    ports:
      - "3011:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/staff_development?sslmode=disable
    depends_on:
      - db
    restart: always

  user_api:
    build:
      context: ./user_api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./user_api:/usr/src/app
    ports:
      - "3002:3002"
    depends_on:
      - db
    env_file: ./.env

  user_db_gui:
    image: sosedoff/pgweb
    ports:
      - "3012:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/user_development?sslmode=disable
    depends_on:
      - db
    restart: always

  inquiry_api:
    build:
      context: ./inquiry_api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./inquiry_api:/usr/src/app
    ports:
      - "3003:3003"
    depends_on:
      - db
    env_file: ./.env

  inquiry_db_gui:
    image: sosedoff/pgweb
    ports:
      - "3013:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/inquiry_development?sslmode=disable
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
