apiVersion: batch/v1
kind: Job
metadata:
  name: batch
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: batch
          image: ghcr.io/kurupeku/crm-sample/inquiry-api:latest
      restartPolicy: Never
  backoffLimit: 10
