apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:15.4-alpine3.18
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "512Mi"
              cpu: "2"
          volumeMounts:
            - name: db-sql
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASSWORD
      volumes:
        - name: db-sql
          configMap:
            name: db-sql
            items:
              - key: init.sql
                path: init.sql
