apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff_api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staff_api
  template:
    metadata:
      labels:
        app: staff_api
    spec:
      containers:
        - name: staff_api
          image: ghcr.io/kurupeku/crm-sample/staff-api:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: db-config
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/app-config
              readOnly: true
            - name: db-config-volume
              mountPath: /etc/db-config
              readOnly: true
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
        - name: db-config-volume
          configMap:
            name: db-config
