apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staff-api
  template:
    metadata:
      labels:
        app: staff-api
    spec:
      containers:
        - name: staff-api
          image: ghcr.io/kurupeku/crm-sample/staff-api:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: db-config
