apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: ghcr.io/kurupeku/crm-sample/user-api:latest
          command:
            - "/bin/sh"
            - "-c"
            - "rails db:migrate && rails s -p 3002 -b '0.0.0.0' -e production"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: db-config
