import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Address = {
  __typename?: 'Address';
  building?: Maybe<Scalars['String']>;
  city: Scalars['String'];
  createdAt: Scalars['Int'];
  fullAddress: Scalars['String'];
  fullAddressWithPostalCode: Scalars['String'];
  id: Scalars['ID'];
  postalCode: Scalars['String'];
  prefecture: Scalars['String'];
  street: Scalars['String'];
  updatedAt: Scalars['Int'];
  userId: Scalars['Int'];
};

/** Autogenerated input type of ChangeProgressRank */
export type ChangeProgressRankInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  rank: ProgressRankEnum;
};

/** Autogenerated input type of ChangeProgressStaff */
export type ChangeProgressStaffInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  staffId: Scalars['Int'];
};

/** Autogenerated input type of ChangeProgressState */
export type ChangeProgressStateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  event: ProgressEventEnum;
  id: Scalars['ID'];
};

export type Comment = {
  __typename?: 'Comment';
  content: Scalars['String'];
  createdAt: Scalars['Int'];
  id: Scalars['ID'];
  inquiry: Inquiry;
  inquiryId: Scalars['Int'];
  staff?: Maybe<Staff>;
  updatedAt: Scalars['Int'];
  user?: Maybe<User>;
  userId: Scalars['Int'];
};

export type CommentsList = {
  __typename?: 'CommentsList';
  comments: Array<Comment>;
  pageInfo: PageInfo;
};

export type CreateAddressInput = {
  building?: Maybe<Scalars['String']>;
  city: Scalars['String'];
  postalCode: Scalars['String'];
  prefecture: Scalars['String'];
  street: Scalars['String'];
};

/** Autogenerated input type of CreateComment */
export type CreateCommentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  content: Scalars['String'];
  inquiryId: Scalars['Int'];
  userId: Scalars['Int'];
};

/** Autogenerated input type of CreateInquiry */
export type CreateInquiryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  companyName?: Maybe<Scalars['String']>;
  detail?: Maybe<Scalars['String']>;
  email: Scalars['String'];
  introductoryTerm: Scalars['String'];
  menuIds?: Maybe<Array<Scalars['Int']>>;
  name: Scalars['String'];
  numberOfUsers: Scalars['Int'];
  progress?: Maybe<CreateProgressInput>;
  tel: Scalars['String'];
  userId?: Maybe<Scalars['Int']>;
};

/** Autogenerated input type of CreateMenu */
export type CreateMenuInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  name: Scalars['String'];
  publishedOn?: Maybe<Scalars['String']>;
};

export type CreateProgressInput = {
  rank?: Maybe<Scalars['Int']>;
  staffId?: Maybe<Scalars['Int']>;
  state?: Maybe<Scalars['String']>;
};

/** Autogenerated input type of CreateUser */
export type CreateUserInput = {
  address: CreateAddressInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  companyName?: Maybe<Scalars['String']>;
  email: Scalars['String'];
  name: Scalars['String'];
  tel: Scalars['String'];
};

/** Autogenerated input type of DeleteComment */
export type DeleteCommentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated input type of DeleteInquiry */
export type DeleteInquiryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated input type of DeleteMenu */
export type DeleteMenuInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated input type of DeleteUser */
export type DeleteUserInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

export type InquiriesList = {
  __typename?: 'InquiriesList';
  inquiries: Array<Inquiry>;
  pageInfo: PageInfo;
};

export type Inquiry = {
  __typename?: 'Inquiry';
  comments: Array<Comment>;
  companyName?: Maybe<Scalars['String']>;
  createdAt: Scalars['Int'];
  detail?: Maybe<Scalars['String']>;
  email: Scalars['String'];
  id: Scalars['ID'];
  introductoryTerm: Scalars['String'];
  menus: Array<Menu>;
  name: Scalars['String'];
  numberOfUsers: Scalars['Int'];
  progress: Progress;
  tel: Scalars['String'];
  updatedAt: Scalars['Int'];
  user?: Maybe<User>;
  userId?: Maybe<Scalars['Int']>;
};

export type Menu = {
  __typename?: 'Menu';
  createdAt: Scalars['Int'];
  id: Scalars['ID'];
  inquiries: Array<Inquiry>;
  name: Scalars['String'];
  publishedOn?: Maybe<Scalars['String']>;
  updatedAt: Scalars['Int'];
};

export type MenusList = {
  __typename?: 'MenusList';
  menus: Array<Menu>;
  pageInfo: PageInfo;
};

export type Mutation = {
  __typename?: 'Mutation';
  changeProgressRank?: Maybe<Progress>;
  changeProgressStaff?: Maybe<Progress>;
  changeProgressState?: Maybe<Progress>;
  changeStaffPassword: Staff;
  createComment?: Maybe<Comment>;
  createInquiry?: Maybe<Inquiry>;
  createMenu?: Maybe<Menu>;
  createStaff: Staff;
  createUser?: Maybe<User>;
  deleteComment?: Maybe<Comment>;
  deleteInquiry?: Maybe<Inquiry>;
  deleteMenu?: Maybe<Menu>;
  deleteStaff: Staff;
  deleteStaffIcon: Staff;
  deleteUser?: Maybe<User>;
  updateComment?: Maybe<Comment>;
  updateInquiry?: Maybe<Inquiry>;
  updateMenu?: Maybe<Menu>;
  updateStaff: Staff;
  updateUser?: Maybe<User>;
  uploadStaffIcon: Staff;
};


export type MutationChangeProgressRankArgs = {
  input: ChangeProgressRankInput;
};


export type MutationChangeProgressStaffArgs = {
  input: ChangeProgressStaffInput;
};


export type MutationChangeProgressStateArgs = {
  input: ChangeProgressStateInput;
};


export type MutationChangeStaffPasswordArgs = {
  input?: Maybe<StaffChangePasswordInput>;
};


export type MutationCreateCommentArgs = {
  input: CreateCommentInput;
};


export type MutationCreateInquiryArgs = {
  input: CreateInquiryInput;
};


export type MutationCreateMenuArgs = {
  input: CreateMenuInput;
};


export type MutationCreateStaffArgs = {
  input?: Maybe<NewStaffInput>;
};


export type MutationCreateUserArgs = {
  input: CreateUserInput;
};


export type MutationDeleteCommentArgs = {
  input: DeleteCommentInput;
};


export type MutationDeleteInquiryArgs = {
  input: DeleteInquiryInput;
};


export type MutationDeleteMenuArgs = {
  input: DeleteMenuInput;
};


export type MutationDeleteStaffArgs = {
  input?: Maybe<StaffIdInput>;
};


export type MutationDeleteStaffIconArgs = {
  input?: Maybe<StaffIdInput>;
};


export type MutationDeleteUserArgs = {
  input: DeleteUserInput;
};


export type MutationUpdateCommentArgs = {
  input: UpdateCommentInput;
};


export type MutationUpdateInquiryArgs = {
  input: UpdateInquiryInput;
};


export type MutationUpdateMenuArgs = {
  input: UpdateMenuInput;
};


export type MutationUpdateStaffArgs = {
  input?: Maybe<StaffInput>;
};


export type MutationUpdateUserArgs = {
  input: UpdateUserInput;
};


export type MutationUploadStaffIconArgs = {
  input?: Maybe<StaffIconInput>;
};

export type NewStaffInput = {
  email: Scalars['String'];
  name: Scalars['String'];
  password: Scalars['String'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  currentPage: Scalars['Int'];
  limit: Scalars['Int'];
  pagesCount: Scalars['Int'];
  recordsCount: Scalars['Int'];
};

export type Progress = {
  __typename?: 'Progress';
  contactedAt?: Maybe<Scalars['Int']>;
  createdAt: Scalars['Int'];
  id: Scalars['ID'];
  inquiry: Inquiry;
  inquiryId: Scalars['Int'];
  rank: Scalars['String'];
  recontactedOn?: Maybe<Scalars['String']>;
  selectableEvents: Array<ProgressEvent>;
  staff: Staff;
  staffId?: Maybe<Scalars['Int']>;
  state?: Maybe<Scalars['String']>;
  updatedAt: Scalars['Int'];
};

export type ProgressEvent = {
  __typename?: 'ProgressEvent';
  event: Scalars['String'];
  label: Scalars['String'];
};

export enum ProgressEventEnum {
  Archive = 'archive',
  Contact = 'contact',
  Contacted = 'contacted',
  Order = 'order',
  Recontact = 'recontact'
}

export enum ProgressRankEnum {
  A = 'a',
  B = 'b',
  C = 'c',
  D = 'd'
}

export enum ProgressStateEnum {
  Archived = 'archived',
  Contacting = 'contacting',
  Estimating = 'estimating',
  Ordered = 'ordered',
  Waiting = 'waiting',
  WaitingRecontact = 'waiting_recontact'
}

export type ProgressesList = {
  __typename?: 'ProgressesList';
  pageInfo: PageInfo;
  progresses: Array<Progress>;
};

export type Query = {
  __typename?: 'Query';
  comment?: Maybe<Inquiry>;
  comments: Array<Comment>;
  commentsList: CommentsList;
  inquiries: Array<Inquiry>;
  inquiriesList: InquiriesList;
  menu?: Maybe<Menu>;
  menus: Array<Menu>;
  menusList: MenusList;
  progress?: Maybe<Progress>;
  progresses: Array<Progress>;
  progressesList: ProgressesList;
  staff: Staff;
  staffList: StaffList;
  staffs: Array<Staff>;
  user?: Maybe<User>;
  users: Array<User>;
  usersList: UsersList;
};


export type QueryCommentArgs = {
  id: Scalars['ID'];
};


export type QueryCommentsArgs = {
  order?: Maybe<Scalars['String']>;
};


export type QueryCommentsListArgs = {
  order?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
};


export type QueryInquiriesArgs = {
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
  staffId?: Maybe<Scalars['Int']>;
};


export type QueryInquiriesListArgs = {
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
  staffId?: Maybe<Scalars['Int']>;
};


export type QueryMenuArgs = {
  id: Scalars['ID'];
};


export type QueryMenusArgs = {
  order?: Maybe<Scalars['String']>;
};


export type QueryMenusListArgs = {
  order?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
};


export type QueryProgressArgs = {
  id: Scalars['ID'];
};


export type QueryProgressesArgs = {
  order?: Maybe<Scalars['String']>;
  rank?: Maybe<ProgressRankEnum>;
  staffId?: Maybe<Scalars['Int']>;
  state?: Maybe<ProgressStateEnum>;
};


export type QueryProgressesListArgs = {
  order?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
  rank?: Maybe<ProgressRankEnum>;
  staffId?: Maybe<Scalars['Int']>;
  state?: Maybe<ProgressStateEnum>;
};


export type QueryStaffArgs = {
  id: Scalars['ID'];
};


export type QueryStaffListArgs = {
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
};


export type QueryUserArgs = {
  id: Scalars['Int'];
};


export type QueryUsersArgs = {
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
};


export type QueryUsersListArgs = {
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
};

export type Staff = {
  __typename?: 'Staff';
  comments: Array<Comment>;
  createdAt: Scalars['String'];
  email: Scalars['String'];
  icon?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name: Scalars['String'];
  progresses: Array<Progress>;
  updatedAt: Scalars['String'];
};

export type StaffChangePasswordInput = {
  id: Scalars['ID'];
  newPassword: Scalars['String'];
  password: Scalars['String'];
};

export type StaffIdInput = {
  id: Scalars['ID'];
};

export type StaffIconInput = {
  icon: Scalars['String'];
  id: Scalars['ID'];
};

export type StaffInput = {
  email?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
};

export type StaffList = {
  __typename?: 'StaffList';
  pageInfo: StaffPageInfo;
  staffs: Array<Staff>;
};

export type StaffPageInfo = {
  __typename?: 'StaffPageInfo';
  currentPage: Scalars['Int'];
  limit: Scalars['Int'];
  pageCount: Scalars['Int'];
  recordCount: Scalars['Int'];
};

export type UpdateAddressInput = {
  building?: Maybe<Scalars['String']>;
  city: Scalars['String'];
  postalCode: Scalars['String'];
  prefecture: Scalars['String'];
  street: Scalars['String'];
};

/** Autogenerated input type of UpdateComment */
export type UpdateCommentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  content: Scalars['String'];
  id: Scalars['ID'];
};

/** Autogenerated input type of UpdateInquiry */
export type UpdateInquiryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  companyName?: Maybe<Scalars['String']>;
  detail?: Maybe<Scalars['String']>;
  email?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  introductoryTerm?: Maybe<Scalars['String']>;
  menuIds?: Maybe<Array<Scalars['Int']>>;
  name?: Maybe<Scalars['String']>;
  numberOfUsers?: Maybe<Scalars['Int']>;
  progress?: Maybe<UpdateProgressInput>;
  tel?: Maybe<Scalars['String']>;
  userId?: Maybe<Scalars['Int']>;
};

/** Autogenerated input type of UpdateMenu */
export type UpdateMenuInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
  publishedOn?: Maybe<Scalars['String']>;
};

export type UpdateProgressInput = {
  rank?: Maybe<Scalars['Int']>;
  staffId?: Maybe<Scalars['Int']>;
  state?: Maybe<Scalars['String']>;
};

/** Autogenerated input type of UpdateUser */
export type UpdateUserInput = {
  address?: Maybe<UpdateAddressInput>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  companyName?: Maybe<Scalars['String']>;
  email?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  name?: Maybe<Scalars['String']>;
  tel?: Maybe<Scalars['String']>;
};

export type User = {
  __typename?: 'User';
  address: Address;
  comments: Array<Comment>;
  companyName?: Maybe<Scalars['String']>;
  createdAt: Scalars['Int'];
  email: Scalars['String'];
  id: Scalars['ID'];
  inquiries: Array<Inquiry>;
  name: Scalars['String'];
  tel: Scalars['String'];
  updatedAt: Scalars['Int'];
};

export type UsersList = {
  __typename?: 'UsersList';
  pageInfo: PageInfo;
  users: Array<User>;
};

export type GetStaffsQueryVariables = Exact<{ [key: string]: never; }>;


export type GetStaffsQuery = { __typename?: 'Query', staffs: Array<{ __typename?: 'Staff', id: string, name: string, email: string, icon?: string | null | undefined, createdAt: string, updatedAt: string }> };

export type GetStaffByIdQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type GetStaffByIdQuery = { __typename?: 'Query', staff: { __typename?: 'Staff', id: string, name: string, email: string, icon?: string | null | undefined, createdAt: string, updatedAt: string } };

export type GetStaffWithCommentsByIdQueryVariables = Exact<{
  staffId: Scalars['ID'];
}>;


export type GetStaffWithCommentsByIdQuery = { __typename?: 'Query', staff: { __typename?: 'Staff', id: string, name: string, email: string, icon?: string | null | undefined, createdAt: string, updatedAt: string, comments: Array<{ __typename?: 'Comment', id: string, userId: number, inquiryId: number, content: string, createdAt: number, updatedAt: number }> } };

export type GetStaffWithProgressesByIdQueryVariables = Exact<{
  staffId: Scalars['ID'];
}>;


export type GetStaffWithProgressesByIdQuery = { __typename?: 'Query', staff: { __typename?: 'Staff', id: string, name: string, email: string, icon?: string | null | undefined, createdAt: string, updatedAt: string, progresses: Array<{ __typename?: 'Progress', id: string, staffId?: number | null | undefined, inquiryId: number, rank: string, state?: string | null | undefined, recontactedOn?: string | null | undefined, contactedAt?: number | null | undefined, createdAt: number, updatedAt: number }> } };

export type GetStaffsListQueryVariables = Exact<{
  page?: Maybe<Scalars['Int']>;
  per?: Maybe<Scalars['Int']>;
}>;


export type GetStaffsListQuery = { __typename?: 'Query', staffList: { __typename?: 'StaffList', staffs: Array<{ __typename?: 'Staff', id: string, name: string, email: string, icon?: string | null | undefined, createdAt: string, updatedAt: string }>, pageInfo: { __typename?: 'StaffPageInfo', currentPage: number, limit: number, pageCount: number, recordCount: number } } };

export type GetUsersQueryVariables = Exact<{
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
}>;


export type GetUsersQuery = { __typename?: 'Query', users: Array<{ __typename?: 'User', id: string, companyName?: string | null | undefined, name: string, email: string, tel: string, createdAt: number, updatedAt: number }> };

export type GetUsersWithAddressQueryVariables = Exact<{
  fieldsCont?: Maybe<Scalars['String']>;
  order?: Maybe<Scalars['String']>;
}>;


export type GetUsersWithAddressQuery = { __typename?: 'Query', users: Array<{ __typename?: 'User', id: string, companyName?: string | null | undefined, name: string, email: string, tel: string, createdAt: number, updatedAt: number, address: { __typename?: 'Address', postalCode: string, prefecture: string, city: string, street: string, building?: string | null | undefined } }> };


export const GetStaffsDocument = gql`
    query getStaffs {
  staffs {
    id
    name
    email
    icon
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetStaffsQuery__
 *
 * To run a query within a React component, call `useGetStaffsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetStaffsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetStaffsQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetStaffsQuery(baseOptions?: Apollo.QueryHookOptions<GetStaffsQuery, GetStaffsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetStaffsQuery, GetStaffsQueryVariables>(GetStaffsDocument, options);
      }
export function useGetStaffsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetStaffsQuery, GetStaffsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetStaffsQuery, GetStaffsQueryVariables>(GetStaffsDocument, options);
        }
export type GetStaffsQueryHookResult = ReturnType<typeof useGetStaffsQuery>;
export type GetStaffsLazyQueryHookResult = ReturnType<typeof useGetStaffsLazyQuery>;
export type GetStaffsQueryResult = Apollo.QueryResult<GetStaffsQuery, GetStaffsQueryVariables>;
export const GetStaffByIdDocument = gql`
    query getStaffById($id: ID!) {
  staff(id: $id) {
    id
    name
    email
    icon
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetStaffByIdQuery__
 *
 * To run a query within a React component, call `useGetStaffByIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetStaffByIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetStaffByIdQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetStaffByIdQuery(baseOptions: Apollo.QueryHookOptions<GetStaffByIdQuery, GetStaffByIdQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetStaffByIdQuery, GetStaffByIdQueryVariables>(GetStaffByIdDocument, options);
      }
export function useGetStaffByIdLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetStaffByIdQuery, GetStaffByIdQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetStaffByIdQuery, GetStaffByIdQueryVariables>(GetStaffByIdDocument, options);
        }
export type GetStaffByIdQueryHookResult = ReturnType<typeof useGetStaffByIdQuery>;
export type GetStaffByIdLazyQueryHookResult = ReturnType<typeof useGetStaffByIdLazyQuery>;
export type GetStaffByIdQueryResult = Apollo.QueryResult<GetStaffByIdQuery, GetStaffByIdQueryVariables>;
export const GetStaffWithCommentsByIdDocument = gql`
    query getStaffWithCommentsById($staffId: ID!) {
  staff(id: $staffId) {
    id
    name
    email
    icon
    createdAt
    updatedAt
    comments {
      id
      userId
      inquiryId
      content
      createdAt
      updatedAt
    }
  }
}
    `;

/**
 * __useGetStaffWithCommentsByIdQuery__
 *
 * To run a query within a React component, call `useGetStaffWithCommentsByIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetStaffWithCommentsByIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetStaffWithCommentsByIdQuery({
 *   variables: {
 *      staffId: // value for 'staffId'
 *   },
 * });
 */
export function useGetStaffWithCommentsByIdQuery(baseOptions: Apollo.QueryHookOptions<GetStaffWithCommentsByIdQuery, GetStaffWithCommentsByIdQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetStaffWithCommentsByIdQuery, GetStaffWithCommentsByIdQueryVariables>(GetStaffWithCommentsByIdDocument, options);
      }
export function useGetStaffWithCommentsByIdLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetStaffWithCommentsByIdQuery, GetStaffWithCommentsByIdQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetStaffWithCommentsByIdQuery, GetStaffWithCommentsByIdQueryVariables>(GetStaffWithCommentsByIdDocument, options);
        }
export type GetStaffWithCommentsByIdQueryHookResult = ReturnType<typeof useGetStaffWithCommentsByIdQuery>;
export type GetStaffWithCommentsByIdLazyQueryHookResult = ReturnType<typeof useGetStaffWithCommentsByIdLazyQuery>;
export type GetStaffWithCommentsByIdQueryResult = Apollo.QueryResult<GetStaffWithCommentsByIdQuery, GetStaffWithCommentsByIdQueryVariables>;
export const GetStaffWithProgressesByIdDocument = gql`
    query getStaffWithProgressesById($staffId: ID!) {
  staff(id: $staffId) {
    id
    name
    email
    icon
    createdAt
    updatedAt
    progresses {
      id
      staffId
      inquiryId
      rank
      state
      recontactedOn
      contactedAt
      createdAt
      updatedAt
    }
  }
}
    `;

/**
 * __useGetStaffWithProgressesByIdQuery__
 *
 * To run a query within a React component, call `useGetStaffWithProgressesByIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetStaffWithProgressesByIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetStaffWithProgressesByIdQuery({
 *   variables: {
 *      staffId: // value for 'staffId'
 *   },
 * });
 */
export function useGetStaffWithProgressesByIdQuery(baseOptions: Apollo.QueryHookOptions<GetStaffWithProgressesByIdQuery, GetStaffWithProgressesByIdQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetStaffWithProgressesByIdQuery, GetStaffWithProgressesByIdQueryVariables>(GetStaffWithProgressesByIdDocument, options);
      }
export function useGetStaffWithProgressesByIdLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetStaffWithProgressesByIdQuery, GetStaffWithProgressesByIdQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetStaffWithProgressesByIdQuery, GetStaffWithProgressesByIdQueryVariables>(GetStaffWithProgressesByIdDocument, options);
        }
export type GetStaffWithProgressesByIdQueryHookResult = ReturnType<typeof useGetStaffWithProgressesByIdQuery>;
export type GetStaffWithProgressesByIdLazyQueryHookResult = ReturnType<typeof useGetStaffWithProgressesByIdLazyQuery>;
export type GetStaffWithProgressesByIdQueryResult = Apollo.QueryResult<GetStaffWithProgressesByIdQuery, GetStaffWithProgressesByIdQueryVariables>;
export const GetStaffsListDocument = gql`
    query getStaffsList($page: Int, $per: Int) {
  staffList(page: $page, per: $per) {
    staffs {
      id
      name
      email
      icon
      createdAt
      updatedAt
    }
    pageInfo {
      currentPage
      limit
      pageCount
      recordCount
    }
  }
}
    `;

/**
 * __useGetStaffsListQuery__
 *
 * To run a query within a React component, call `useGetStaffsListQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetStaffsListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetStaffsListQuery({
 *   variables: {
 *      page: // value for 'page'
 *      per: // value for 'per'
 *   },
 * });
 */
export function useGetStaffsListQuery(baseOptions?: Apollo.QueryHookOptions<GetStaffsListQuery, GetStaffsListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetStaffsListQuery, GetStaffsListQueryVariables>(GetStaffsListDocument, options);
      }
export function useGetStaffsListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetStaffsListQuery, GetStaffsListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetStaffsListQuery, GetStaffsListQueryVariables>(GetStaffsListDocument, options);
        }
export type GetStaffsListQueryHookResult = ReturnType<typeof useGetStaffsListQuery>;
export type GetStaffsListLazyQueryHookResult = ReturnType<typeof useGetStaffsListLazyQuery>;
export type GetStaffsListQueryResult = Apollo.QueryResult<GetStaffsListQuery, GetStaffsListQueryVariables>;
export const GetUsersDocument = gql`
    query getUsers($fieldsCont: String, $order: String) {
  users(fieldsCont: $fieldsCont, order: $order) {
    id
    companyName
    name
    email
    tel
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetUsersQuery__
 *
 * To run a query within a React component, call `useGetUsersQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetUsersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetUsersQuery({
 *   variables: {
 *      fieldsCont: // value for 'fieldsCont'
 *      order: // value for 'order'
 *   },
 * });
 */
export function useGetUsersQuery(baseOptions?: Apollo.QueryHookOptions<GetUsersQuery, GetUsersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetUsersQuery, GetUsersQueryVariables>(GetUsersDocument, options);
      }
export function useGetUsersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetUsersQuery, GetUsersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetUsersQuery, GetUsersQueryVariables>(GetUsersDocument, options);
        }
export type GetUsersQueryHookResult = ReturnType<typeof useGetUsersQuery>;
export type GetUsersLazyQueryHookResult = ReturnType<typeof useGetUsersLazyQuery>;
export type GetUsersQueryResult = Apollo.QueryResult<GetUsersQuery, GetUsersQueryVariables>;
export const GetUsersWithAddressDocument = gql`
    query getUsersWithAddress($fieldsCont: String, $order: String) {
  users(fieldsCont: $fieldsCont, order: $order) {
    id
    companyName
    name
    email
    tel
    createdAt
    updatedAt
    address {
      postalCode
      prefecture
      city
      street
      building
    }
  }
}
    `;

/**
 * __useGetUsersWithAddressQuery__
 *
 * To run a query within a React component, call `useGetUsersWithAddressQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetUsersWithAddressQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetUsersWithAddressQuery({
 *   variables: {
 *      fieldsCont: // value for 'fieldsCont'
 *      order: // value for 'order'
 *   },
 * });
 */
export function useGetUsersWithAddressQuery(baseOptions?: Apollo.QueryHookOptions<GetUsersWithAddressQuery, GetUsersWithAddressQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetUsersWithAddressQuery, GetUsersWithAddressQueryVariables>(GetUsersWithAddressDocument, options);
      }
export function useGetUsersWithAddressLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetUsersWithAddressQuery, GetUsersWithAddressQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetUsersWithAddressQuery, GetUsersWithAddressQueryVariables>(GetUsersWithAddressDocument, options);
        }
export type GetUsersWithAddressQueryHookResult = ReturnType<typeof useGetUsersWithAddressQuery>;
export type GetUsersWithAddressLazyQueryHookResult = ReturnType<typeof useGetUsersWithAddressLazyQuery>;
export type GetUsersWithAddressQueryResult = Apollo.QueryResult<GetUsersWithAddressQuery, GetUsersWithAddressQueryVariables>;