// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStaffInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type StaffInput struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Email *string `json:"email"`
}
