// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID string `json:"id"`
}

func (Comment) IsEntity() {}

type NewStaffInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Progress struct {
	ID string `json:"id"`
}

func (Progress) IsEntity() {}

type StaffChangePasswordInput struct {
	ID          string `json:"id"`
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type StaffIDInput struct {
	ID string `json:"id"`
}

type StaffIconInput struct {
	ID   string `json:"id"`
	Icon string `json:"icon"`
}

type StaffInput struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

type StaffsList struct {
	PageInfo *StaffPageInfo `json:"pageInfo"`
	Staffs   []*Staff       `json:"staffs"`
}
