apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config_map/app_config.yaml
  - deployment/auth_api.yaml
  - deployment/database.yaml
  - deployment/federation.yaml
  - deployment/gateway.yaml
  - deployment/inquiry_api.yaml
  - deployment/staff_api.yaml
  - deployment/user_api.yaml
  - job/db_seed.yaml
  - service/auth_api.yaml
  - service/database.yaml
  - service/federation.yaml
  - service/inquiry_api.yaml
  - service/staff_api.yaml
  - service/user_api.yaml
