name: Auth API Test

on:
  workflow_dispatch:
  push:
    paths:
      - "auth_api/**/**.go"

defaults:
  run:
    working-directory: ./auth_api

jobs:
  test-auth-api:
    name: Test Auth API
    runs-on: ubuntu-latest
    env:
      GO_ENV: production
      GO111MODULE: on
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64

    services:
      db:
        image: postgres:15.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: db
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: auth_api/go.mod
          cache: true

      - name: Get dependencies
        run: go get .

      - name: Test
        run: |
          go test -v ./...
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          GO_ENV: test

      - name: Vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false

      - name: Try Building
        run: go build main.go
