name: Build and Push Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ghcr.io/kurupeku/crm-sample

jobs:
  batch-image:
    name: Batch Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: batch

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}

  gateway-image:
    name: Gateway Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: gateway

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}

  federation-image:
    name: Federation Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: federation

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}

  auth-api-image:
    name: Auth API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: auth_api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}

  staff-api-image:
    name: Staff API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: staff_api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}

  user-api-image:
    name: User API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: user_api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            SECRET_KEY_BASE=${{ secrets.USER_API_SECRET_KEY_BASE }}

  inquiry-api-image:
    name: Inquiry API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DIR_NAME: inquiry_api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tags
        run: |
          TAG_BASE=${IMAGE_NAME_BASE}/$(echo $DIR_NAME | sed -e 's/_/-/g')
          echo "TAGS=$TAG_BASE:${{ github.sha }},$TAG_BASE:latest" >> "$GITHUB_ENV"

      - name: Build and Push '${{ env.DIR_NAME }}' image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_NAME }}
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            SECRET_KEY_BASE=${{ secrets.INQUIRY_API_SECRET_KEY_BASE }}
