name: Staff API Test

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - main
    paths:
      - "staff_api/**/**.go"

env:
  API_NAME: staff_api
  GO_ENV: production
  GOOS: linux
  GOARCH: amd64

defaults:
  run:
    working-directory: ./staff_api

jobs:
  test-staff-api:
    name: Test Staff API
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: db
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.API_NAME }}/go.mod
          cache: true
          cache-dependency-path: ${{ env.API_NAME }}/go.sum

      - name: Get dependencies
        run: go get .

      - name: Test
        run: |
          go test -v ./...
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          GO_ENV: test

      - name: Vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          working-directory: ${{ env.API_NAME }}

      - name: Try Building
        run: go build main.go
