name: User API Test

on:
  workflow_dispatch:

  push:
    paths:
      - "user_api/**"

defaults:
  run:
    working-directory: ./user_api

jobs:
  test-user-api:
    name: Test User API
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: db
          POSTGRES_HOST_AUTH_METHOD: trust

    container:
      image: ruby:3
      env:
        DB_HOST: db
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_PORT: 5432

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Setup postgres client
        run: |
          apt-get update -qq
          apt-get install -yq postgresql-client

      - name: Install bundles
        run: bundle install -j4

      - name: Create and setup Database
        run: |
          bundle exec rails db:setup

      - name: Run Rspec
        run: |
          bundle exec rspec
