name: User API Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "user_api/**"
    branches-ignore:
      - main

defaults:
  run:
    working-directory: ./user_api

jobs:
  test-user-api:
    name: Test User API
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432

    services:
      db:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out branch
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ./user_api
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install bundles
        run: bundle install -j4

      - name: Create and setup Database
        run: |
          bundle exec rails db:setup

      - name: Run Rspec
        run: |
          bundle exec rspec
